version: "3.8"

services:

  database:
    container_name: database
    image: postgres:13.4
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: facilitajuridico
      POSTGRES_PASSWORD: root
    networks:
      - facilitajuridico_net
    volumes:
      - database_facilitajuridico:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "3333:3333"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - facilitajuridico_net
    depends_on:
      - "database"
    command: npm run start:dev

    frontend:
        build:
          context: ./frontend
        container_name: frontend
        ports:
          - "5173:5173"
        volumes:
          - ./frontend:/usr/src/app
        tty: true
        networks:
          - facilitajuridico_net
        depends_on:
          - "api"
        command: npm run dev

volumes:
  database_facilitajuridico:
    driver: local

networks:
  facilitajuridico_net:
    driver: bridge
