CREATE TABLE IF NOT EXISTS clients (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  dddphone VARCHAR(2) NOT NULL,
  phone VARCHAR(9) NOT NULL,
  createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedat TIMESTAMP DEFAULT NULL,
  deletedat TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS routes (
  id SERIAL PRIMARY KEY,
  clientid INTEGER NOT NULL,
  xcoordinate INT NOT NULL,
  ycoordinate INT NOT NULL,
  createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedat TIMESTAMP DEFAULT NULL,
  deletedat TIMESTAMP DEFAULT NULL,
  CONSTRAINT fk_client FOREIGN KEY (clientid) REFERENCES clients (id) ON DELETE CASCADE ON UPDATE CASCADE
);