CREATE TABLE IF NOT EXISTS clients (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  dddphone VARCHAR(2) NOT NULL,
  phone VARCHAR(9) NOT NULL,
  createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedat TIMESTAMP DEFAULT NULL,
  deletedat TIMESTAMP DEFAULT NULL
);

ALTER TABLE clients
ADD COLUMN xcoordinate INT DEFAULT NULL,
ADD COLUMN ycoordinate INT DEFAULT NULL;